"""config.py — paths, env loading, and shared constants."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CACHE_DIR = DATA_DIR / "cache"
MODELS_DIR = PROJECT_ROOT / "models"

FOOTBALL_DATA_CACHE_DIR = CACHE_DIR / "football_data"
ODDS_CACHE_DIR = CACHE_DIR / "odds"
FPL_HISTORY_CACHE_DIR = CACHE_DIR / "fpl_history"
FPL_PLAYER_CACHE_DIR = CACHE_DIR / "fpl_players"
FPL_EVENT_CACHE_DIR = CACHE_DIR / "fpl_events"
UNDERSTAT_CACHE_DIR = CACHE_DIR / "understat"
# One file per MATCH, not per season (unlike every other cache dir here) —
# see data/understat_shots.py's module docstring.
UNDERSTAT_SHOTS_CACHE_DIR = CACHE_DIR / "understat_shots"
PULSELIVE_CACHE_DIR = CACHE_DIR / "pulselive"

COMPETITION = "ENG Premier League"

ODDS_API_KEY = os.getenv("ODDS_API_KEY")
ODDS_API_SPORT_KEY = "soccer_epl"
ODDS_API_BASE_URL = "https://api.the-odds-api.com/v4/sports"

FPL_API_BASE_URL = "https://fantasy.premierleague.com/api"
FPL_HISTORY_BASE_URL = "https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data"

# football-data.org: current-season fixtures/results/standings in one call
# each, no per-day workaround needed (unlike API-Football's free tier,
# which walls off the current season entirely) — see data/football_data_org.py.
FOOTBALL_DATA_KEY = os.getenv("FOOTBALL_DATA_KEY")
FOOTBALL_DATA_ORG_BASE_URL = "https://api.football-data.org/v4"
FOOTBALL_DATA_ORG_COMPETITION_ID = 2021  # Premier League

ESPN_SCOREBOARD_URL = "https://site.api.espn.com/apis/site/v2/sports/soccer/eng.1"

# pulselive.com: the Premier League's own site backend — no key, no
# documented terms. Used only as a fast current-season supplement to
# football-data.co.uk (whose CSV publishing can lag indefinitely) — private,
# non-redistributed personal use only. See data/pulselive.py.
PULSELIVE_BASE_URL = "https://footballapi.pulselive.com/football"
PULSELIVE_COMPETITION_ID = 1  # Premier League

# Not in cache/: unlike everything else there, this can't be regenerated by
# re-fetching — it's the accumulated record of what the model predicted
# *before* each match kicked off, which only exists if it was captured at
# the time.
TRACKING_DB_PATH = DATA_DIR / "tracking.db"

for _d in (
    DATA_DIR,
    CACHE_DIR,
    MODELS_DIR,
    FOOTBALL_DATA_CACHE_DIR,
    ODDS_CACHE_DIR,
    FPL_HISTORY_CACHE_DIR,
    FPL_PLAYER_CACHE_DIR,
    FPL_EVENT_CACHE_DIR,
    UNDERSTAT_CACHE_DIR,
    UNDERSTAT_SHOTS_CACHE_DIR,
    PULSELIVE_CACHE_DIR,
):
    _d.mkdir(parents=True, exist_ok=True)
